name: Bug report
description: File a bug report to help improve zk-nvim.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
  - type: checkboxes
    id: checks
    attributes:
      label: Check if applicable
      description: |
        :warning: At the moment, there are no official lua maintainer for this project. Your bug report might be ignored, no hard feelings.
        :heart: But if you would like to contribute a fix yourself, **I'll be happy to review a pull request**.
      options:
        - label: I have searched the existing issues (**required**)
          required: true
        - label: I'm willing to help fix the problem and contribute a pull request
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Also tell me, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-steps
    attributes:
      label: How to reproduce?
      description: |
        Step by step explanation to reproduce the issue.

        If you can, drag and drop:
        - a zipped sample notebook
        - screenshots or a screencast showing the issue
      placeholder: |
        1. Add a note with the content "..."
        2. Run `:ZKNew`
        3. See error
        ...
    validations:
      required: true
  - type: textarea
    id: zk-config
    attributes:
      label: zk configuration
      description: |
        Paste the minimal `zk` configuration file (`.zk/config.toml`) reproducing the issue.
      render: toml
    validations:
      required: true
  - type: textarea
    id: vim-config
    attributes:
      label: Neovim configuration
      description: |
        Paste the minimal Neovim configuration file (`init.vim` or `init.lua`) reproducing the issue.
      render: viml
    validations:
      required: true
  - type: textarea
    id: bug-environment
    attributes:
      label: Environment
      description: |
        Run the following shell commands and paste the result here:
        ```
        zk --version && echo "system: `uname -srmo`" && nvim --version
        ```
      placeholder: |
        zk 0.13.0
        system: Darwin 22.5.0 arm64
        NVIM v0.9.0
        Build type: Release
        LuaJIT 2.1.0-beta3

           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.0/share/nvim"

        Run :checkhealth for more info
      render: bash
